language: node_js
node_js: 8
script:
- npm run lint
- npm run build
deploy:
  provider: npm
  email: wrlach@gmail.com
  skip-cleanup: true
  on:
    tags: true
    repo: metricsgraphics/react-metrics-graphics
  api_key:
    secure: bB4GDcMKkzJKD29WVrASc+IyBAt1A8dOHWY6C9kFTPI0y2Dv3nuSSdcBxO+849dlDGjafDW+SuGhqtLUJCRa4eQKkp5UDj/8jFa40HCe4rGCy5R/LL2xDylLd/b+lWB7ulMouKxESJwpoSp2XxA7FZ9JUAFCNMT5nkIREN9oB2teOyRtjDCTeeHg4AwwUR0ap2aELt+bwcirCRpdZ2aDDaX63Vr/V8C1H/GoCGKBYUHxhRHgnq/Su3EmQ+/LpIEyZ/sNcPo3LsyI+RgD/A26CRFzq5iv/E55HxVEwrOkKIym2AlPqwG3XllCoKkyRNqErsVRolmUF6uV8HfpDW5rAJuXVwPSi55m9CSToiJOKFL+xmFGfxnUv0EvX5+zTheGrc8M4G9u8mD91NOQwRYGuj1RLHCDsYBJtKVF5hORvYO5ICf6XeJ8m2KMdOaS6d7E38fFtSvLu5LN9r3cj6G4OM4LwBqL6a3rCzig7UZD2XBINiHkoOkhgoHKzocynLeF7KKOxmZbSsQGEi+0ZC7e1Fh6vXOLvRBGSn1IdEbruR9a4POlPAsStPGlMlMFlMgMcx/xhiHP0zoUOoXyhb/TulM0O4JUIDfOCQv9EMHsJQNjLgKMIjTB9qzCl7Eudu8rs+rxm1iIQ3AyxOx2w2B161YF3pJtGCLixyrJGb9UNEk=
